language: go
go_import_path: github.com/kevinburke/test-fmt-repro

os: linux
dist: trusty
sudo: false

before_script:
  - go get ./...

script:
  - go test ./...

go:
  - 1.10.x
  - 1.11.x
  - master

cache:
  directories:
    - $GOPATH/pkg
